<a href="https://colab.research.google.com/github/Altaieb-Mohammed/pytorch-tutorial-YouTube-/blob/main/intro_To_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np

In [ ]:
my_list = [1,2,3,4,5],[6,7,8,9,10]
my_list

([1, 2, 3, 4, 5], [6, 7, 8, 9, 10])

In [ ]:
np1 = np.random.rand(3,4)
np1

array([[0.34950323, 0.70195156, 0.40996729, 0.81743555],
       [0.73279122, 0.7344054 , 0.19031974, 0.20597189],
       [0.74329612, 0.25955212, 0.23428082, 0.93408612]])

In [ ]:
np1.dtype

dtype('float64')

In [ ]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[ 0.7216,  0.6401, -0.8971, -0.1384],
        [ 0.2204, -0.7820,  1.5430, -0.6579],
        [ 0.1212, -0.9994,  0.7265,  0.4746]])

In [ ]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
#create a tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.3495, 0.7020, 0.4100, 0.8174],
        [0.7328, 0.7344, 0.1903, 0.2060],
        [0.7433, 0.2596, 0.2343, 0.9341]], dtype=torch.float64)